version: "3.8"
volumes:
  db-store:
services:
  mysql:
    build: ./docker/mysql
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: kotlin_sample_app
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d